### ISSUE TITLE
It did grab all of my blog,but almost all of them are empty

### ISSUE THREAD

**Issue by RedemptionC** [ame-yu/CSDN-export-script#2]
what could be the reason?
My os is ubuntu 20.04 LTS
I use the script to grab my blogs,then unzip them
And I found all of them are empty:
```
...
-rw-rw-r--  1 andy andy   0 8月  28 13:46 'xv6 risc-v file system logging layer.md'
-rw-rw-r--  1 andy andy   0 8月  28 13:46 'xv6 risc-v file system 笔记.md'
-rw-rw-r--  1 andy andy   0 8月  28 13:46 'xv6 risc-v inode相关代码 walk through.md'
-rw-rw-r--  1 andy andy   0 8月  28 13:46 'xv6 risc-v kalloc.c code walk through.md'
-rw-rw-r--  1 andy andy   0 8月  28 13:46 'xv6 risc-v lock notes.md'
-rw-rw-r--  1 andy andy   0 8月  28 13:46 'xv6 risc-v scheduler 笔记.md'
...
```

**Comment by ame-yu** [comment]
Does Devtools console show any error?
And what's your browser? Need more infomation.

**Comment by RedemptionC** [comment]
> Does Devtools console show any error?
> And what's your browser you are using? Need more information.

I'm using chrome
there are some error message:
```
hm.js:1 Failed to load resource: net::ERR_CONNECTION_CLOSED
jweixin-1.3.2.js:1 Failed to load resource: net::ERR_CONNECTION_CLOSED
blog-console-api.csdn.net/:1 Failed to load resource: the server responded with a status of 404 ()
A bad HTTP response code (404) was received when fetching the script.
hm.js:1 Failed to load resource: net::ERR_CONNECTION_CLOSED
baidu-search.js?_=1630249339631:1 GET https://gsp0.baidu.com/yrwHcjSl0MgCo2Kml5_Y_D3/api/customsearch/apiaccept?sid=10742016945123576423&v=2.0&callback=csdn.afterBaiduSearchInit net::ERR_CONNECTION_CLOSED
baiduSearchInstall @ baidu-search.js?_=1630249339631:1
(anonymous) @ baidu-search.js?_=1630249339631:1
(anonymous) @ baidu-search.js?_=1630249339631:1
var s=document.createElement('script');s.type='text/javascript';document.body.appendChild(s);s.src='//cdn.jsdelivr.net/gh/ame-yu/csdn-move@latest/dist/index.js';

"//cdn.jsdelivr.net/gh/ame-yu/csdn-move@latest/dist/index.js"
```

**Comment by RedemptionC** [comment]
but when I check the response in the network panel,there are contents of my blog

**Comment by ame-yu** [comment]
Sorry, I have no idea what's going on here. I guess it cound be some issue when saving blob data to ubuntu. I'll upgrade dependency and build it again. Hope it resolve your problem.

**Comment by ame-yu** [comment]
```
var s=document.createElement('script');s.type='text/javascript';document.body.appendChild(s);s.src='https://cdn.jsdelivr.net/gh/ame-yu/CSDN-export-script@dev/dist/index.js'
```

**Comment by RedemptionC** [comment]
> Sorry, I have no idea what's going on here. I guess it cound be some issue when saving blob data to ubuntu. I'll upgrade dependency and build it again. Hope it resolve your problem.

it's  probably not due  to ubuntu,it doesn't work on my windows laptop either

**Comment by ame-yu** [comment]
You could download your post in pure javascript.(download separately). paste follow code to browser console.
And run it with `getPage(<PageNumber>)`. Good luck.
```
function download(filename, text) {
  var element = document.createElement("a");
  element.setAttribute(
    "href",
    "data:text/plain;charset=utf-8," + encodeURIComponent(text)
  );
  element.setAttribute("download", filename);

  element.style.display = "none";
  document.body.appendChild(element);

  element.click();

  document.body.removeChild(element);
}

function getPage(num = 1) {
  const ConsoleApi = {
    page: "https://blog-console-api.csdn.net/v1/article/list?page=",
    article: "https://blog-console-api.csdn.net/v1/editor/getArticle?id=",
  };

  const pageUrl = (num) => `${ConsoleApi.page}${num}`;
  const articleUrl = (id) => `${ConsoleApi.article}${id}`;
  var count = 1;
  async function nextPage(page) {
    const url = pageUrl(page);
    let rsp = await (await fetch(url)).json();
    if (!rsp.data.list || rsp.data.list.length === 0) return;
    if (rsp.code !== 200) {
      alert("导出失败。未登录或API已变动。查看Console,前去提交issue吧");
    }
    let total = rsp.data.total;
    for (info of rsp.data.list) {
      const url = articleUrl(info.ArticleId);
      let rsp = await (await fetch(url)).json();
      const title = rsp.data.title.replace(/\/|\\/g, "_");
      download(`${title}.md`, rsp.data.markdowncontent);
      document.title = `📦 [${count++}/${total}] 已打包`;
    }
  }
  nextPage(num);
}
```
![202108301002](https://user-images.githubusercontent.com/42380973/131275234-946a3ee8-49eb-45d8-91b7-7695ba68c3c7.gif)

**Comment by RedemptionC** [comment]
@ame-yu 
didn't work
```
getPage()
undefined
blog.js:1 GET https://blog-console-api.csdn.net/v1/article/list?page=1 401
(anonymous) @ blog.js:1
e @ blog.js:1
nextPage @ VM130:28
getPage @ VM130:42
(anonymous) @ VM149:1
VM130:29 Uncaught (in promise) TypeError: Cannot read property 'list' of undefined
    at nextPage (<anonymous>:29:19)
```

**Comment by ame-yu** [comment]
Did you run code in page https://blog-console-api.csdn.net/.
It looks like you have a CORS restriction error.

**Comment by RedemptionC** [comment]
>Did you run code in page https://blog-console-api.csdn.net/ ?

@ame-yu I checked again,it did download something,but all of them are empty

**Comment by ame-yu** [comment]
Can I see your screenshots in network pannel like this one?
![image](https://user-images.githubusercontent.com/42380973/131312078-35f85377-194d-4fc9-aced-d6c78b3fa05c.png)

**Comment by RedemptionC** [comment]
@ame-yu of course
![image](https://user-images.githubusercontent.com/17563754/131312472-6a0d1385-4ba3-44e4-b372-9422af9fc212.png)

**Comment by ame-yu** [comment]
If data.markdowncontent was not empty. Then fucntion `download` does not working properly.
What's your chrome version? go check `chrome://version/`

**Comment by RedemptionC** [comment]
> If data.markdowncontent was not empty. Then fucntion `download` does not working properly.
> What's your chrome version? go check `chrome://version/`

@ame-yu 
Oh I found that content is not empty,but markdownContent is empty
what could be the reason?

**Comment by ame-yu** [comment]
@RedemptionC
I just register a new account. Then find out the reason.
![image](https://user-images.githubusercontent.com/42380973/131318913-3fe2adde-f75f-4282-86f3-48ef8e8a5e8e.png)
👈Old Editor          New Editor👉
https://editor.csdn.net/md/?not_checkout=1   old 
https://mp.csdn.net/mp_blog/creation/editor  new
I quit CSDN 2 years ago.Then i write this script, publish recently.
Now CSDN using specific formats for post written by new editor.
Of course markdowncontent was empty, cuz it's not standard markdown format anymore.

**Comment by RedemptionC** [comment]
@ame-yu 
got it
maybe I should find another way
thanks for your effort

**Comment by RedemptionC** [comment]
>Now CSDN using specific formats for post written by new editor.
Of course markdowncontent was empty, cuz it's not standard markdown format anymore.

maybe we could add this in the doc

**Comment by ame-yu** [comment]
@RedemptionC I will.
By the way,I'm using [simpread](https://simpread.pro/) to save webpage page to offline markdown.

**Comment by RedemptionC** [comment]
> @RedemptionC I will.
> By the way,I'm using [simpread](https://simpread.pro/) to save web page to offline markdown.

thanks,I will try it
